# GitHub Actions workflow to run tests on Android.
name: "Android"

on:
  workflow_call:

jobs:
  test:
    name: "Test ${{ matrix.name }}"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Android 8-9"
            min-nal: 26
            max-nal: 28
          - name: "Android 10-11"
            min-nal: 29
            max-nal: 30
    steps:
      - name: "Download prepared source"
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: "prepared-source"

      - name: "Extract prepared source"
        run: |
          mkdir source
          tar -xzf libressl-*.tar.gz -C source --strip-components=1

      - name: "Run CI script"
        run: ./scripts/test
        working-directory: source
        env:
          ARCH: "android"
          MIN_NAL: "${{ matrix.min-nal }}"
          MAX_NAL: "${{ matrix.max-nal }}"
          PREPARED_SOURCE: 1
