# GitHub Actions workflow to run for Emscripten.
name: "Emscripten"

on:
  workflow_call:

jobs:
  test:
    name: "Emscripten"
    runs-on: "ubuntu-24.04"
    permissions:
      contents: read
    steps:
      - name: "Download prepared source"
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: "prepared-source"

      - name: "Extract prepared source"
        run: |
          mkdir source
          tar -xzf libressl-*.tar.gz -C source --strip-components=1

      - name: "Install test dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y libio-socket-ssl-perl
          perl -MIO::Socket::SSL::Utils -e 1

      - name: "Setup emsdk"
        uses: mymindstorm/setup-emsdk@4528d102f7230f0e7b276855c01ea1159be0e984 # v16
        with:
          version: "3.1.60"

      - name: "Configure CMake"
        run: emcmake cmake -S source -B build

      - name: "Build"
        run: cmake --build build --config Release

      - name: "Test"
        run: ctest --test-dir build -C Release --output-on-failure

  # Test ASAN with and without ASM enabled.
  test-asan:
    name: "ASAN (no-asm)"
    runs-on: "ubuntu-24.04"
    permissions:
      contents: read
    steps:
      - name: "Download prepared source"
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: "prepared-source"

      - name: "Extract prepared source"
        run: |
          mkdir source
          tar -xzf libressl-*.tar.gz -C source --strip-components=1

      - name: "Install test dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y libio-socket-ssl-perl
          perl -MIO::Socket::SSL::Utils -e 1

      - name: "Setup emsdk"
        uses: mymindstorm/setup-emsdk@4528d102f7230f0e7b276855c01ea1159be0e984 # v16
        with:
          version: "3.1.60"

      - name: "Configure CMake"
        run: emcmake cmake -S source -B build
        env:
          CFLAGS: "-gsource-map -fsanitize=address"
          LDFLAGS: "-fsanitize=address"

      - name: "Build"
        run: cmake --build build --config Release

      - name: "Test"
        run: ctest --test-dir build -C Release --output-on-failure
