# GitHub Actions workflow to run tests on Linux.
name: "Linux"

on:
  workflow_call:

jobs:
  # Test against all supported architectures.
  test:
    name: "${{ matrix.os }}/${{ matrix.arch }} (${{ matrix.compiler }})"
    runs-on: "${{ matrix.os }}"
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04", "ubuntu-24.04"]
        arch: ["native", "arm32", "arm64", "mingw32", "mingw64", "mips32", "mips64"]
        compiler: ["gcc"]
        include:
          - os: "ubuntu-22.04"
            arch: "native"
            compiler: "clang"
          - os: "ubuntu-24.04"
            arch: "native"
            compiler: "clang"
          - os: "ubuntu-24.04" # loong64
            arch: "loong64"
            compiler: "gcc"
          - os: "ubuntu-24.04-arm"
            arch: "native"
            compiler: "gcc"
          - os: "ubuntu-24.04-arm"
            arch: "native"
            compiler: "clang"

    steps:
      - name: "Download prepared source"
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: "prepared-source"

      - name: "Extract prepared source"
        run: |
          mkdir source
          tar -xzf libressl-*.tar.gz -C source --strip-components=1

      - name: "Install test dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y libio-socket-ssl-perl
          perl -MIO::Socket::SSL::Utils -e 1

      - name: "Run tests"
        run: ./scripts/test || (status=$?; cat tests/test-suite.log; exit $status)
        working-directory: source
        env:
          ARCH: "${{ matrix.arch }}"
          CC: "${{ matrix.compiler }}"
          PREPARED_SOURCE: 1

  # Test ASAN with and without ASM enabled.
  test-asan:
    name: "${{ matrix.os }} - ASAN (${{ matrix.asm == 'ON' && 'asm' || 'no-asm' }})"
    runs-on: "${{ matrix.os }}"
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        asm: [ON, OFF]
        os: ["ubuntu-24.04", "ubuntu-24.04-arm"]
    steps:
      - name: "Download prepared source"
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: "prepared-source"

      - name: "Extract prepared source"
        run: |
          mkdir source
          tar -xzf libressl-*.tar.gz -C source --strip-components=1

      - name: "Install test dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y libio-socket-ssl-perl
          perl -MIO::Socket::SSL::Utils -e 1

      - name: "Run tests"
        run: ./scripts/test
        working-directory: source
        env:
          ARCH: "native"
          CC: "clang"
          CFLAGS: "-ggdb -fsanitize=address"
          LDFLAGS: "-fsanitize=address"
          ENABLE_ASM: "${{ matrix.asm }}"
          CTEST_OUTPUT_ON_FAILURE: 1
          PREPARED_SOURCE: 1
